In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1)
b = tf.constant(2)
sess = tf.InteractiveSession()

In [3]:
a.eval()

1

In [4]:
b.eval()

2

In [5]:
c = a+b
d = a*b

In [6]:
c.eval()

3

In [7]:
d.eval()

2

In [8]:
V1 = tf.constant([1,2])
V2 = tf.constant([3,4])
M = tf.constant([[1,2]])
N = tf.constant([[1,2],[3,4]])
K = tf.constant([[[1,2],[3,4]]])

In [9]:
K.eval()

array([[[1, 2],
        [3, 4]]], dtype=int32)

In [10]:
V1.eval()

array([1, 2], dtype=int32)

In [12]:
V2.eval()

array([3, 4], dtype=int32)

In [13]:
M.eval()

array([[1, 2]], dtype=int32)

In [14]:
N.eval()

array([[1, 2],
       [3, 4]], dtype=int32)

In [15]:
V3 = V1 + V2

M2 = M * M

NN = tf.matmul(N,N)

In [16]:
NN.eval()

array([[ 7, 10],
       [15, 22]], dtype=int32)

In [17]:
M2.eval()

array([[1, 4]], dtype=int32)

In [19]:
V3.eval()

array([4, 6], dtype=int32)

In [20]:
output = sess.run(NN)
print("NN is:")
print(output)

NN is:
[[ 7 10]
 [15 22]]


In [21]:
W = tf.Variable(0, name="weight")

In [23]:
init_op = tf.global_variables_initializer()
sess.run(init_op)

In [24]:
W.eval()

0

In [25]:
W +=a
W.eval()

1

In [26]:
W = W + a
W.eval()

2

In [27]:
E = d + b
E.eval()

4

In [28]:
d.eval()

2

In [29]:
sess.run([E,d])

[4, 2]

In [30]:
sess.run(E, feed_dict={d:4,})

6